CREATE TABLE PAIS (ID INT8 NOT NULL, NOME VARCHAR(50) NOT NULL, PRIMARY KEY (ID));

CREATE TABLE ESTADO (ID INT8 NOT NULL, NOME VARCHAR(50) NOT NULL, CODIGO VARCHAR(2), SIGLA VARCHAR(2) NOT NULL, FK_PAIS INT8 NOT NULL, PRIMARY KEY (ID));
ALTER TABLE ESTADO ADD CONSTRAINT FK_ESTADO_PAIS FOREIGN KEY (FK_PAIS) REFERENCES PAIS;

CREATE TABLE CIDADE (ID INT8 NOT NULL, NOME VARCHAR(50) NOT NULL, CODIGO_IBGE VARCHAR(7) NOT NULL, FK_ESTADO INT8 NOT NULL, PRIMARY KEY (ID));
ALTER TABLE CIDADE ADD CONSTRAINT FK_CIDADE_ESTADO FOREIGN KEY (FK_ESTADO) REFERENCES ESTADO;

CREATE TABLE CIDADE_GEOLOCALIZACAO (ID INT8 NOT NULL, FK_CIDADE INT8 NOT NULL, GEOLOCALIZACAO GEOMETRY NOT NULL, PRIMARY KEY (ID));
ALTER TABLE CIDADE_GEOLOCALIZACAO ADD CONSTRAINT FK_CIDADE_GEOLOCALIZACAO_CIDADE FOREIGN KEY (FK_CIDADE) REFERENCES CIDADE;